# Project: Detecting Emotions from Text
https://www.nlplanet.org/course-practical-nlp/02-practical-nlp-first-tasks/08-emotion-classification

In [2]:
from datasets import load_dataset
from transformers import pipeline
import pandas as pd
import plotly.express as px

In [7]:
# download the tweets dataset
#dataset = load_dataset("carblacac/twitter-sentiment-analysis", split="train",data_dir="C:\temp")

train = pd.read_csv(r"C:\Users\TristramArmour\OneDrive - Innovisk\Documents\data\emotion_tweets\train_150k.txt",sep='\t',header=None)
train.columns=["label","text"]
train.head()

   label                                               text
0      0  Starting  back at work today   Looks like it'l...
1      1  Sugar levels dropping... munchies setting in. ...
2      1     @karineb22 yeah!!! have a great summer break!
3      1  hannah montana was very good.  now going to re...
4      1  @Mayra326 aww, have fun!  I just had my 3D las...

In [9]:
# keep only the tweets with a specific filter word. Let's try with "microsoft"
filter_word = "microsoft"
df_subset = train[train["text"].str.lower().str.contains(filter_word)].reset_index(drop=True)
df_subset

    label                                               text
0       1  Searching for Susan Boyle on Microsoft's Bing ...
1       0  @tonyadam @oilman just more proof that Microso...
2       0  Microsoft just doesn't get it  Check out their...
3       0       it's so sad how I can't use MY microsoft!!!
4       1  @aMmadz yea more often than earlier i'd say, w...
5       0  @Kaboro unless you mind reading on the compute...
6       1  @danlev I'd like to remind you of the most imp...
7       1  Kurt Moody packed the #Citrix booth at #teched...
8       1  Oh shit, Yoko Ono is at e3....she's going to b...
9       1  @_everaldo Entourage *has* a really ugly inter...
10      0               Studying for another Microsoft exam
11      0  hmmm not sure about this microsoft blutooth mo...
12      1  @kwats So @Chris_Anderson just said that Micro...
13      0  Very sad  Microsoft money to be discontinue ht...
14      0  @mattrogowski Happened to me when downloading ...
15      1  &quot;I'm using Microsoft Office.I'm just grat...
16      1  Microsoft Stops Paying For Employees' iPhones ...
17      1  everyone who plays xbox check thos place out h...
18      1  Hey, Microsofts BING is live! That's 2 days ea...
19      1  Its been 30 min and Microsoft has shown us 4 m...
20      1    @jasonbirch could be true, bing that microsoft
21      0  Microsoft forcing Bing on IE6 users!?: Shared ...
22      0  @bwana any awesome games must get this year? I...
23      0           long day with microsoft is my nightmare
24      1  Getting ready for E3, 6:25Pm @ http://xbox.com...
25      1  http://ping.fm/LZsLg &quot;Downgrade rights?&q...
26      1  @_Goblin Yeah blame them flame them... what el...
27      0  on top of that, OWA was &quot;protected&quot; ...
28      1  Awesome press conference by Microsoft, also Pr...
29      0  @trixie360 oh btw!Will Microsoft be streaming ...
30      1  Google should launch an OS.. will send Microso...
31      0              @nicepaul See also Microsoft Windows
32      1  @real_microsoft how can apple pretend their ne...
33      1  just updated my laptop with microsoft office  ...
34      0  @Agent_M ah. knowing microsoft, they could pro...
35      1  @Rstarkiller89 Yeah. I'm a bit biased because ...
36      0  my #zune is officially dead.  Please #microsof...
37      1  For once, #microsoft has gotten it right on #b...
38      0   Microsoft Windows Guru program came to an end...
39      1  So Microsoft released Bing, huh? Too bad they ...
40      1  @TheAnand  Microsoft Certified Trainer  hehe.....
41      1  @g4tv Loved Sony's confrence its tied with Mic...
42      0  honestly, why did the folks at Microsoft do MS...
43      0  having a very difficult relationship with Micr...
44      1  Microsofts new phone may come to the UK after ...
45      1  @jesscoburn Huh! It's only beta now. Waiting f...
46      0  Microsoft and Sony have replicated and improve...
47      0  E3 looks awsome this year i missed microsofts ...
48      0  @ThePaul it's a modded 360, so you can't send ...
49      1  I just made my own Crossword Puzzle on Microso...
50      0  Microsoft Bluetooth Mouse is mIssing... Left i...
51      1  heh microsoft deleted new &quot;laptop hunter&...
52      1  @lirimaas it's Microsoft's new search engine (...
53      1  All the Microsoft E3 announcements look simply...
54      0  does microsoft office for mac 2008 excel autos...

In [10]:
# download pre-trained emotion classification model
model = pipeline("text-classification", model="j-hartmann/emotion-english-distilroberta-base")

# compute the emotion of each tweet using the model
all_texts = df_subset["text"].values.tolist()
all_emotions = model(all_texts)
df_subset["emotion_label"] = [d["label"] for d in all_emotions]
df_subset["emotion_score"] = [d["score"] for d in all_emotions]

config.json:   0%|          | 0.00/1.00k [00:00<?, ?B/s]

c:\Users\TristramArmour\anaconda3\envs\learning\Lib\site-packages\huggingface_hub\file_download.py:147: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\TristramArmour\.cache\huggingface\hub\models--j-hartmann--emotion-english-distilroberta-base. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

pytorch_model.bin:   0%|          | 0.00/329M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/294 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

In [11]:
# plot emotions found in tweets
plot_title = f"Emotions found in tweets about '{filter_word}'"
fig = px.histogram(df_subset, x="emotion_label", template="plotly_dark",
                   title=plot_title, color="emotion_label")
fig.update_layout(showlegend=False)
fig.show()

In [12]:
# show sample of tweets with a specific emotion
for i,row in df_subset[df_subset["emotion_label"] == "joy"].iterrows():
  print(f'- {row["text"]}')

- Kurt Moody packed the #Citrix booth at #teched. It also helps when Microsoft serves alcohol   http://twitpic.com/50s3i
- &quot;I'm using Microsoft Office.I'm just grateful anytime i can print&quot;  http://ur1.ca/4z2t
- Awesome press conference by Microsoft, also Project Natal is going to be a BIG HIT
- just updated my laptop with microsoft office  yay now i can use it for school
- @g4tv Loved Sony's confrence its tied with Microsoft for me. Most excited for God Of War 3
- All the Microsoft E3 announcements look simply amazing. Congrats to the whole team!  Can't wait for 09.09.09 to get here now